### ISSUE TITLE
/system/bin/m.mpxmac: No such file or directory

### ISSUE THREAD

**Issue by neozeed** [AZBevier/nbc#1]
totally dont want to bug you on vacation!

its no rush at all im just playing around.

I tried to cross build as I understand from linux but it's missing this command?

```
make[2]: Entering directory '/home/jsteve/src/nbc/nbc-master/nblib'
touch clib
touch cdir
/system/bin/nbcc -Pprefile -c c.srt.s -o c.srt.o
/system/bin/m.mpxmac: No such file or directory
"", line 0: Fatal assembler error (macfile file /system/bin/m.mpxmac)
Assembler abort: AS29
```

I found out I have to add rcs to get the build kicking through the directories as well.

Im stepping through trying to build more manually like this

```
export PATH=/system/bin:$PATH
rm -rf /system
make clean
make clobber
mkdir -p /system/bin
mkdir -p /system/lib
mkdir -p /system/cinclude/sys
touch /system/bin/m.mpxmac
touch /system/lib/m.mpxmac1x
touch /system/lib/mpxpre1x



(cd include;tar -cf - .)|(cd /system/cinclude;tar -xvf -)
cp include/types.h /system/cinclude/sys
cp include/times.h /system/cinclude/sys
cp include/param.h /system/cinclude/sys
cp include/errno.h /system/cinclude/sys
cp include/stat.h /system/cinclude/sys

cd nbyacc
make -f make.unix
mv nbyacc /system/bin
mv yaccpar /system/lib;cd ..

cd nbcpp
make -f make.unix
mv nbcpp /system/bin;cd ..

cd nbccom
make -f make.unix
mv nbccom /system/bin;cd ..

cd nbasm
make -f make.unix
mv nbasm /system/bin;cd ..

cd nbcc
make -f make.unix
mv nbcc /system/bin;cd ..

cd nbar
make -f make.unix
mv nbar /system/bin;cd ..
```

although off to build enough of the system to cross build hello world..

**Comment by AZBevier** [comment]
This issue was caused by an incomplete makefile for NBC.  The makefile now builds all files/programs need to populate the /system directory tree.  I have verified all files are now build under Linux.  The next step is to verify that an MPX32 tape can be created and installed on MPX1X and MPX3X and build/operate correctly.

**Comment by neozeed** [comment]
Awesome!  It's totally cool what you have managed to build!

**Comment by AZBevier** [comment]
neozeed, could you send me an e-mail address I can communicate through with you?  Jim

**Comment by neozeed** [comment]
sure.. I dont see any PM's here ... I dont use github all that much.  Anyways it's ME at GMAIL ...
